# Generated by Django 4.1.4 on 2023-01-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_created',
        ),
    ]
